In [4]:
# important libraries of data science and data analytics

# numpy
# pandas
# matplotlib

In [5]:
# numpy andradhu namoloda list madhiri,

# difference yenana
# list rombha slow , list use paniti , nama yedhavadhu array operations panna , rombha time agum

# adhe numpy arrays use panna, rombha fast ah array operations

In [6]:
import numpy as np   # np andradhu oru alias mattum dha , ni np badhula ajithnu kooda vechikalam, simpele ah solanum na oru nickname
# inumel np andra nickname use panti namma numpy koopdaporam

In [7]:
#import numpy as  # inge ram andradhu oru nickname , numpy ku , numpy andra word use pannama ram nu word use panuvom

In [8]:
my_lt = [9,4,2,5,6,74,3,3]
# idhu oru simple list

In [9]:
type(my_lt) # my_lt andradhu oru list

list

ipo andha list (my_lt) namma numpy array ah mathaporom

In [10]:
arr = np.array(my_lt)   , # inge np library oda array andra function use paniti np.array, namma np.array(my_lt) my_lt oru numpy array ah mathitom, adhuku peru dha arr
# inge arr andradhu oru numpy array ., list kadiaadhu

In [11]:
arr

(array([ 9,  4,  2,  5,  6, 74,  3,  3]),)

In [12]:
# task

# A  list
my_list = [1, 2, 3, 4, 5]

# Convert the list to a NumPy array
my_array = np.array(my_list)

print(my_array)
print(type(my_array))   # numpy array nu varum,,, n dimensional array, inge n is 1 dimension, since it is a one dimensional array

[1 2 3 4 5]
<class 'numpy.ndarray'>


Why NumPy instead of normal Python lists?

In [13]:
#python list
a = [1, 2, 3]
b = [4, 5, 6]

a + b      # inge addition nadakala , joining dha nadakadhi

[1, 2, 3, 4, 5, 6]

In [14]:

import numpy as np
my_list = [4,3,5,7,8,9]
my_array = np.array(my_list)
print(my_array)
print(type(my_array))

[4 3 5 7 8 9]
<class 'numpy.ndarray'>


In [15]:
# ipo numpy arrays use panalam, same operation kaga
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b         # inge addition nadandhichi

array([5, 7, 9])

In [ ]:
# arange function use paniti 5,98 varakum print pandrom , arange(5,99) will give an array of numbers from 5 to 98

In [16]:
np.arange(5,99)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98])

In [17]:
# step size 8 , inge array range 10 to 200 meaning 10 landhi 199 varakum oru array create agum , aana step size 8 meaning oru oru element nadula gap(difference)8 irukum
# 10,18,26,34......ipidi 199 varakum pogum,, first 10 adhoda adutha element 10+8 (18),, adhoda adutha element 26 (18+8), adhoda adutha element 34(26+8)
# indhamari step size add ayiti next element vadhite irukum
np.arange(10,200,8)

array([ 10,  18,  26,  34,  42,  50,  58,  66,  74,  82,  90,  98, 106,
       114, 122, 130, 138, 146, 154, 162, 170, 178, 186, 194])

In [18]:
np.zeros(5) # zeros will give an array of zeros , zeros(5) nu kudutha 5 zeros varum , 10 kudutha 10 zeros varum

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((5,4))  # zeros matrix, 5 rows , 4 columns , oru 2 dimensional array matrix create agum.

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# task , create 3x6 zero matrix , meaning 3 rows , 6 columns

In [21]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
# random , inge random.randint use panna , indha function random ah integers create panidum, adhuku dha idhoda peru randint,,,
# indha example la randint(5,120)nu kudthom , meaning,  5 landhi 120 kulla oru integer tharum random ah
# indha cell naraya vati run panna ,different values output ah varum, rendu moonu vati indha cell mattume run pani paru
val = np.random.randint(5,120)
val

95

In [23]:
# inge extra ah irukara parameter 20 , idhu oru step size mari, meaning ,,, namaku 5 landhi 120 nadula ,20 random values venumnu meaning
# run panna 20 values varum random ah , marubadium run panna , inoru 20 different random values varum
val2 = np.random.randint(5,120,20)
val2

array([ 70, 109,   6,  84,  87,  40,  34,  15,  79,  22, 118, 118,  68,
        85,  43,  72, 110,  54,  19,  97])

In [24]:
val3 = np.random.randint(30,90,8) # inge 30 to 90 nadula namaku random ah oru 8 values venum, adha meaning,
#indha cell adikadiki run panna, 8 values different ah varum, but 8 values varum alwys
val3

array([86, 36, 78, 76, 70, 33, 36, 51])

In [25]:
# mela nadakara mari inge kooda random ah values generate pannalam, but idhu konchem different ah work agum
# random.randn,,, inge randn meaning random decimal values between -1 and 1,,,, randn(3) kudutha 3 values create agum , yella values -1 landhi 1 ku nadula dha irukum
random_arr = np.random.randn(3)
random_arr

array([-1.65719214, -0.36481925,  0.66772779])

In [26]:
# oru vela , namma random ah create panna values adikadiki maarakoodadhunu namma nanacha
# random.seed use pannalam, oru seed value use panna , andha seed value ku fixed ah random values oru vati create agum
# aprom indha cell yethanavati run pannalum , yedhume change aagadhu
# indha cell 3 to 4 tyms run pani paru ,,, onnume change aagadhu, orey value varum, because oru seed value ku oru random values fixed ah varum


np.random.seed(101)
fixed_arr = np.random.randint(5,120, 9) # 5 landhi 120 ku nadula 9 values create pandrom but seed value use pannadha nala indha cell yethana vati run pannalum andha 9 values same values ah adha varum
# indha cell naraya vati run pani paru , same 9 values dha varum, maaraadhu, fixed 9 values , reason mela use panna seed function
fixed_arr

array([100,  16,  86,  75,  68,  92,  80, 116,  14])

In [27]:
np.random.seed(90) # seed value andradhu namaloda istam,,eg:- 100, 90, 108,, ipdii yendha value analum use pannalam
fixed_arr2 = np.random.randint(5,120, 9)
fixed_arr2   # so seed value 90 ku vere 9 values varum

array([ 96,  34, 119,  36,  72,  44,  73,  63,  42])

In [28]:
np.random.seed(109) # seed value andradhu namaloda istam,,eg:- 100, 90, 108,, ipdii yendha value analum use pannalam
fixed_arr3 = np.random.randint(45,120, 15)
fixed_arr3

array([ 51,  58,  60,  78,  49, 108,  87, 102,  96,  61,  50, 107,  67,
       109,  97])

In [29]:
# ipo ones pathi pakalam,, ones(6) nu use panna , array having 6 ones varum
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [30]:
ones_Arr = np.ones(10)
ones_Arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
#NUMPY ARRAY size and shape kandupikardhi

In [32]:
arr = np.array([10, 20, 30, 40])

print(arr.shape)  # how many elements
print(arr.size)   # total values

(4,)
4


In [33]:
arr2 = np.array(([10, 20, 30, 40], [3,5,6,2]))

 # [10, 20, 30, 40]
 # [3,   5,  6,  2]

print(arr2.shape)  # how many elements,,, mothama 2 rows, 4 colums irukum , so 2x4 matrix array
print(arr2.size)   # total values  ,, 2x4 total 8 values iriki

(2, 4)
8


In [ ]:
arr3 =  np.arange(1,25)
#ipo indha array la 10 elements irki 5 landhi 14 varkum motham 10,

arr3
# indha array one dimension  ,,, idhu namma 2d array ah (matrix ) ah mathidalam

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [34]:
arr3 = np.arange(1,25)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
twoD_Arr =  arr3.reshape(6,4) # meaning,, mela irukara arr3 la 10 elements iriki adhu 5 rows and 2 columns ah maathaporom
twoD_Arr  # theliva patha, mela irukara elements yellame , 5 rows and 2 colums ah mathiachi
# why 5 rows and 2 colums use pannomna ,, 5x2 10 varum , irukardhi 10 elements so matrix la 10 elements fit agum

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
twoD_Arr = arr3.reshape(6,4)
twoD_Arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [ ]:
twoD_Arr =  arr3.reshape(8,3) # meaning,, mela irukara arr3 la 10 elements iriki adhu 5 rows and 2 columns ah maathaporom
twoD_Arr  # theliva patha, mela irukara elements yellame , 5 rows and 2 colums ah mathiachi
# why 5 rows and 2 colums use pannomna ,, 5x2 10 varum , irukardhi 10 elements so matrix la 10 elements fit agum

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [ ]:
twoD_Arr = arr3.reshape(8,3)
twoD_Arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [35]:
twoD_Arr =  arr3.reshape(12,2) # meaning,, mela irukara arr3 la 10 elements iriki adhu 5 rows and 2 columns ah maathaporom
twoD_Arr  # theliva patha, mela irukara elements yellame , 5 rows and 2 colums ah mathiachi
# why 5 rows and 2 colums use pannomna ,, 5x2 10 varum , irukardhi 10 elements so matrix la 10 elements fit agum

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [ ]:
twoD_Arr = arr3.reshape(12,2)
twoD_Arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [ ]:
twoD_Arr =  arr3.reshape(3,8) # meaning,, mela irukara arr3 la 10 elements iriki adhu 5 rows and 2 columns ah maathaporom
twoD_Arr  # theliva patha, mela irukara elements yellame , 5 rows and 2 colums ah mathiachi
# why 5 rows and 2 colums use pannomna ,, 5x2 10 varum , irukardhi 10 elements so matrix la 10 elements fit agum

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
twoD_Arr = arr3.reshape(3,8)
twoD_Arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
twoD_Arr2 =  arr3.reshape(4,6) # meaning,, mela irukara arr3 la 10 elements iriki adhu 2 rows and 5 columns ah maathaporom
twoD_Arr2  # inge 2 rows 5 colums , motham 2x5 10 elements

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
twoD_Arr2 = arr3.reshape(4,6)
twoD_Arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [ ]:
twoD_Arr2 =  arr3.reshape(2,12) # meaning,, mela irukara arr3 la 10 elements iriki adhu 2 rows and 5 columns ah maathaporom
twoD_Arr2  # inge 2 rows 5 colums , motham 2x5 10 elements

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
twoD_Arr2 = arr3.reshape(2,12)
twoD_Arr2

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [36]:
arr = np.array([1, 4, 9])  # math functiosn pakalam

In [37]:
print(np.sqrt(arr))  # square root
print(np.sum(arr))   # sum
print(np.mean(arr))   # average
print(np.max(arr))    # max
print(np.min(arr))    # min

[1. 2. 3.]
14
4.666666666666667
9
1


In [38]:
arr = np.array([10, 20, 30, 40])   # indexing , lists la namma pakaramari dha , no big changes

print(arr[0])   # first element 10
print(arr[-1])  # last element  40
print(arr[2])   # third element 30

10
40
30


In [39]:
# slicing kooda same dha , lists la pakaramari numpy la kooda

arr = np.array([10, 50, 80, 20, 30, 90, 40])
# slice andradhu array ah cut paniti oru part thania yedukaramari
arr[2:5]  # 2:5 meaning 2nd index la irukara element landhi 4 index element varkum
# inge 2nd index la irukardi 80 , so 80 landhi 20, 30 varkum varum since 30 4th index , 5th index consider aagadhu

array([80, 20, 30])

In [40]:
arr[1:4]   # frist indexx landhi , 3rd index varkum varum

array([50, 80, 20])

In [41]:
arr[:6]    # starting landi yella elements , till 5th index
# 0 1 2 3 4 5

array([10, 50, 80, 20, 30, 90])

In [42]:
arr[3:]  # 3rd index landhi last element varakum

#3, 4, 5, 6 index

array([20, 30, 90, 40])

In [ ]:
arr = np.array([10, 40, 70, 20, 28, 30, 90, 40])

print(arr > 25)   # array values greater than 25 values ,,, 25 mela irukara array values mattume true varum

#10false, 40true, 70true, 20false,,,,,,,,,,,,,

[False  True  True False  True  True  True  True]


In [ ]:
print(arr[arr > 25])  # array values greater than 25 values ,,, 25 mela irukara array values mattume varum,

[40 70 28 30 90 40]


In [ ]:
arr = np.arange(3, 20)

print(arr)                # 3 landhi 19 varakum....             [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
print(arr * 3)            # multiplied by 3                     [ 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57]
print(arr[arr % 2 == 0])  # 2 divisable elements mattume varum  [ 2  4  6  8 10]

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57]
[ 4  6  8 10 12 14 16 18]
